clean:remove copy
	cp conf1.txt conf.txt
copy:
	cp -R Client1 Client2
	cp -R Client1 Client3
	cp -R Client1 Client4
	cp -R Client1 Client5
	cp -R Client1 Client6
	cp -R Client1 Client7
	cp -R Client1 Client8
	cp -R Client1 Client9
	cp -R Client1 Client10
remove:
	rm -rvf Client2 Client3 Client4 Client5 Client6 Client7 Client8 Client9 Client10
	
